name: PR Request Checks

on:
  pull_request:
    types: ["opened", "synchronize", "auto_merge_enabled"]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkov GitHub Action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          skip_check: CKV_TF_1 # TODO: add module/template versioning
          framework: terraform
      - name: terraform validate
        run: |
          terraform init
          terraform validate
          echo validated
